pub fn explorer_tx_url(chain_id: u16, tx_hash: &str) -> Option<String> {
    match chain_id {
        1 => Some(format!("https://explorer.solana.com/tx/{tx_hash}")),
        2 => Some(format!("https://etherscan.io/tx/{tx_hash}")),
        4 => Some(format!("https://bscscan.com/tx/{tx_hash}")),
        5 => Some(format!("https://polygonscan.com/tx/{tx_hash}")),
        6 => Some(format!("https://snowtrace.io/tx/{tx_hash}")),
        13 => Some(format!("https://kaiascan.io/tx/{tx_hash}")),
        14 => Some(format!("https://celoscan.io/tx/{tx_hash}")),
        15 => Some(format!("https://nearblocks.io/txns/{tx_hash}")),
        16 => Some(format!("https://moonscan.io/tx/{tx_hash}")),
        23 => Some(format!("https://arbiscan.io/tx/{tx_hash}")),
        24 => Some(format!("https://optimistic.etherscan.io/tx/{tx_hash}")),
        25 => Some(format!("https://gnosisscan.io/tx/{tx_hash}")),
        30 => Some(format!("https://basescan.org/tx/{tx_hash}")),
        32 => Some(format!("https://seitrace.com/tx/{tx_hash}")),
        34 => Some(format!("https://scrollscan.com/tx/{tx_hash}")),
        38 => Some(format!("https://lineascan.build/tx/{tx_hash}")),
        39 => Some(format!("https://berascan.com/tx/{tx_hash}")),
        43 => Some(format!("https://explorer.snaxchain.io/tx/{tx_hash}")),
        44 => Some(format!("https://uniscan.xyz/tx/{tx_hash}")),
        45 => Some(format!("https://worldscan.org/tx/{tx_hash}")),
        46 => Some(format!("https://explorer.inkonchain.com/tx/{tx_hash}")),
        47 => Some(format!("https://explorer.hyperliquid.xyz/tx/{tx_hash}")),
        50 => Some(format!("https://explorer.mezo.org/tx/{tx_hash}")),
        52 => Some(format!("https://sonicscan.org/tx/{tx_hash}")),
        55 => Some(format!("https://explorer.plume.org/tx/{tx_hash}")),
        57 => Some(format!("https://explorer.xrplevm.org/tx/{tx_hash}")),
        63 => Some(format!("https://explorer.mocachain.io/tx/{tx_hash}")),
        64 => Some(format!("https://www.megaexplorer.xyz/tx/{tx_hash}")),
        _ => None,
    }
}
